version: '3'

services:
  postgres:
    build:
      ./infra/postgres/
    ports:
      - "5432:5432" # needed for monitoring purposes only
    environment:
      POSTGRES_PASSWORD: "docker" # todo: make it var
  kafka:
    build:
      ./infra/kafka/
#    ports: # enable this to get access to dashboard
#      - "2181:2181"
#      - "3030:3030"
#      - "8081-8083:8081-8083"
#      - "9581-9585:9581-9585"
#      - "9092:9092"
  producer:
    build:
      ./infra/target/
    depends_on:
      - kafka
    command: dshw_producer.py
    environment:
      KAFKA_ADDRESS: "kafka:9092"
      KAFKA_TOPIC: "dshw-topic" # todo: use vars
  consumer:
    build:
      ./infra/target/
    depends_on:
      - kafka
      - postgres
      - producer
    command: dshw_consumer.py
    environment:
      KAFKA_ADDRESS: "kafka:9092"
      KAFKA_TOPIC: "dshw-topic" # todo: use vars
      PG_CONNECTION_STR: "postgresql+psycopg2://postgres:docker@postgres:5432/monitor"
